#ifndef BOARD_H
#define BOARD_H

#include <REG52.H>
#include <ABSACC.H>

typedef unsigned char u8;
typedef unsigned int u16;
typedef unsigned long u32;

/*
 * Target board: P-A-1 temperature/humidity board, STC89C54RD+.
 * Crystal on the schematic: 12 MHz.
 */
#define FOSC_HZ 12000000UL

/*
 * 8255 mapping from the reference schematic:
 *   D0..D7 -> P0 bus
 *   A0/A1  -> latched A0/A1
 *   /RD    -> P3.7 external /RD
 *   /WR    -> P3.6 external /WR
 *   /CS    -> P2.6 line
 *
 * Use 0x0480 instead of 0x0080 to avoid the low MOVX address range
 * that STC89C54RD+ may map to on-chip expanded RAM.
 *   0x0480 > 0x03FF: outside the common low internal XRAM area.
 *   Low byte 0x80 keeps A7=1, so ADC0809 decode stays disabled.
 *   High byte 0x04 keeps P2.6=0, matching the 8255 active-low /CS.
 *   A0/A1 still select PA/PB/PC/CTRL through the low address bits.
 *
 * If a board still does not drive the external bus, a fallback is to set
 * the STC AUXR EXTRAM bit in i8255_init(), but do not enable that together
 * with this address change until the 0x0480 diagnostic tests are checked.
 */
#define PPI_BASE_ADDR 0x0480
#define PPI_PORT_A XBYTE[PPI_BASE_ADDR + 0]
#define PPI_PORT_B XBYTE[PPI_BASE_ADDR + 1]
#define PPI_PORT_C XBYTE[PPI_BASE_ADDR + 2]
#define PPI_CTRL   XBYTE[PPI_BASE_ADDR + 3]

/*
 * 8255 ports on display/IO sheet:
 *   PA0..PA7 -> LK0..LK7 -> 74HC240 -> LED0..LED7
 *   PB0..PB7 -> dp,g,f,e,d,c,b,a segment bus
 *   PC0..PC7 -> SK0..SK7 switch inputs
 */
#define LED_ACTIVE_HIGH 1
#define SWITCH_ACTIVE_LOW 0

/*
 * ADC0809 mapping from the schematic:
 *   D0..D7 -> P0 bus
 *   ADD-A/B/C -> latched A0/A1/A2
 *   START/ALE and OE are generated by /WR, /RD and A7 logic.
 *   EOC -> P3.2
 *
 * Use A7=0 to enable ADC0809 logic through the 74HC02 gates.
 * Use P2.6=1 to keep the 8255 deselected during ADC access.
 * Address form: 0x4000 + channel.
 */
#define ADC0809_BASE_ADDR 0x4000
#define ADC0809_REG(ch) XBYTE[ADC0809_BASE_ADDR + ((ch) & 0x07)]
sbit ADC0809_EOC = P3^2;

/* DHT11 data pin on sheet 2. */
sbit DHT11_IO = P3^3;

/* Six digit select lines drive ULN2003 inputs P1.0..P1.5. */
#define DIGIT_PORT P1
#define DIGIT_KEEP_MASK 0xC0

/* Serial assistant unlock byte for the first task step. */
#define PA1_UNLOCK_BYTE 'A'

#endif
